const portfolioData = {
  experience: [
    {
      role: "Backend AI Engineer",
      org: "FlyRank AI",
      status: "Present",
      statusClass: "present",
      date: "Jun 2026 — Present",
      points: [
        "Develop and integrates LLMs.",
        "Fix APIs and observes, optimization."
      ]
    },
    {
      role: "Media Director",
      org: "Unilever",
      status: "Present",
      statusClass: "present",
      date: "Jun 2024 — Apr 2025 & Aug 2025 — Present",
      points: [
        "Deploy and planning for upcoming video projects for advertisement.",
        "Make sure to maintain proper location, spot, shoot time, golden ratio and perfect combination of models.",
        "Edit the raw files, do the color grade and create the perfect AD to post on social media.",
        "Research social media to know what the audience would love to see and what it would need to do for that particular product promo."
      ]
    },
    {
      role: "Senior Video Creator",
      org: "Forward Tech (Part-Time)",
      status: "Concluded",
      statusClass: "concluded",
      date: "Feb 2025 — Nov 2025",
      points: [
        "Edited client-supplied footage end-to-end, from raw cut to final delivery.",
        "Built motion-graphics edits across light and combination video styles.",
        "Produced 3D animation sequences for client deliverables."
      ]
    },
    {
      role: "Coordinator, Media Team",
      org: "IEEE NSU Student Branch",
      status: "Concluded",
      statusClass: "concluded",
      date: "Mar 2025 — Aug 2025",
      points: [
        "Led the videography team producing promotional video for the branch.",
        "Led the photography team covering every branch-organized event.",
        "Directed post-processing for the wider media team.",
        "Drove the SPAC 2025 promotional video campaign."
      ]
    },
    {
      role: "In-Charge, Media Team",
      org: "IEEE NSU Student Branch",
      status: "Concluded",
      statusClass: "concluded",
      date: "Sep 2023 — Jan 2025",
      points: [
        "Headed videography, photography and post-processing across branch media.",
        "Headed the media team for SPAC."
      ]
    },
    {
      role: "Core Volunteer, Media Team",
      org: "IEEE NSU Student Branch",
      status: "Concluded",
      statusClass: "concluded",
      date: "Sep 2022 — Sep 2023",
      points: [
        "Led photography coverage across branch events.",
        "Handled post-processing for the media team."
      ]
    }
  ],
  skills: [
    {
      sectorNum: "Sector 01",
      title: "Languages & Web",
      items: [
        { icon: "https://skillicons.dev/icons?i=python", name: "Python" },
        { icon: "https://skillicons.dev/icons?i=js", name: "JavaScript" },
        { icon: "https://skillicons.dev/icons?i=ts", name: "TypeScript" },
        { icon: "https://skillicons.dev/icons?i=java", name: "Java" },
        { icon: "https://skillicons.dev/icons?i=cpp", name: "C / C++" },
        { icon: "https://skillicons.dev/icons?i=php", name: "PHP" },
        { icon: "https://skillicons.dev/icons?i=mysql", name: "MySQL" },
        { icon: "https://skillicons.dev/icons?i=html", name: "HTML" },
        { icon: "https://skillicons.dev/icons?i=css", name: "CSS" }
      ]
    },
    {
      sectorNum: "Sector 02",
      title: "Frameworks & ML",
      items: [
        { icon: "https://skillicons.dev/icons?i=react", name: "React" },
        { icon: "https://skillicons.dev/icons?i=nextjs", name: "Next.js" },
        { icon: "https://skillicons.dev/icons?i=django", name: "Django" },
        { icon: "https://skillicons.dev/icons?i=pytorch", name: "PyTorch" },
        { icon: "https://skillicons.dev/icons?i=tensorflow", name: "TensorFlow" },
        { icon: "https://skillicons.dev/icons?i=opencv", name: "OpenCV" }
      ]
    },
    {
      sectorNum: "Sector 03",
      title: "Tools & Devops",
      items: [
        { icon: "https://skillicons.dev/icons?i=git", name: "Git" },
        { icon: "https://skillicons.dev/icons?i=github", name: "GitHub" },
        { icon: "https://skillicons.dev/icons?i=linux", name: "Linux" },
        { icon: "https://skillicons.dev/icons?i=vercel", name: "Vercel" },
        { icon: "https://skillicons.dev/icons?i=postman", name: "Postman" }
      ]
    },
    {
      sectorNum: "Sector 04",
      title: "Creative Software",
      items: [
        { icon: "https://skillicons.dev/icons?i=photoshop", name: "Photoshop" },
        { icon: "https://skillicons.dev/icons?i=ai", name: "Illustrator" },
        { icon: "https://skillicons.dev/icons?i=ae", name: "After Effects" },
        { icon: "https://skillicons.dev/icons?i=pr", name: "Premiere Pro" },
        { icon: "https://skillicons.dev/icons?i=blender", name: "Blender 3D" },
        { icon: "https://cdn.simpleicons.org/davinciresolve", name: "DaVinci Resolve" },
        { icon: "data:image/svg+xml,%3Csvg width='256' height='256' viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='256' height='256' rx='60' fill='%23001E36'/%3E%3Ctext x='128' y='175' font-family='Arial' font-weight='bold' font-size='120' fill='%2331A8FF' text-anchor='middle'%3ELr%3C/text%3E%3C/svg%3E", name: "Lightroom" },
        { icon: "data:image/svg+xml,%3Csvg width='256' height='256' viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='256' height='256' rx='60' fill='%23111111'/%3E%3Ctext x='128' y='170' font-family='Arial' font-weight='bold' font-size='90' fill='%23FFFFFF' text-anchor='middle'%3ECapCut%3C/text%3E%3C/svg%3E", name: "CapCut" },
        { icon: "https://skillicons.dev/icons?i=au", name: "Audition" }
      ]
    }
  ],
  projects: [
    {
      num: "01",
      title: "MindGPT",
      description: "Multilingual mental-wellness chatbot with RAG, built on Ollama (Gemma3, Llama3.2, Qwen) and a Django backend. Includes a patient–doctor system with dynamic prescriptions.",
      tags: ["Django", "RAG", "LLM"],
      category: "AI / Web App",
      link: "https://github.com/itisFAHIM/Mental-Health-Chatbot-with-Booking-System",
      image: "images/MindGPT.png"
    },
    {
      num: "02",
      title: "IdentiFind",
      description: "Knowledge-base-free framework for person profile disambiguation — real-time face matching, automated profile generation, built on TensorFlow & PyTorch.",
      tags: ["TensorFlow", "PyTorch", "CV"],
      category: "Computer Vision",
      link: "https://github.com/itzjunayed/CSE499-Project-IdentiFind",
      image: null
    },
    {
      num: "03",
      title: "Personal Coding Agent — Korbi",
      description: "Offline, private coding assistant powered by DeepSeek R1 for reasoning and LLaVA 7B for image input, with voice in/out and a Django backend for dynamic model swapping.",
      tags: ["DeepSeek R1", "LLaVA", "Django"],
      category: "AI Agent",
      link: "https://github.com/itisFAHIM/Personal-Chatbot",
      image: "images/Personal Coding Agent.png"
    },
    {
      num: "04",
      title: "Aqua Sync Smart Water Pump",
      description: "Full-stack digital-twin platform for a smart water-pump product line — admin control panel, live telemetry, activity logs and subscription-linked firmware updates.",
      tags: ["TypeScript", "IoT", "Full-Stack"],
      category: "IoT / Full-Stack",
      link: "https://github.com/itisFAHIM/Aqua-Sync-Smart-Water-Pump",
      image: "images/AquaSync.png"
    },
    {
      num: "05",
      title: "Physics Chatbot",
      description: "LLM/SLM-powered chatbot that solves physics problems from easy to hard difficulty, with matrix-based problem modeling and searchable user history.",
      tags: ["LLM", "SLM"],
      category: "AI / Education",
      link: "https://github.com/tamimishrak/physics-chatbot",
      image: null
    },
    {
      num: "06",
      title: "RickShare",
      description: "Ride-sharing platform in active development, aiming at an Uber/Pathao-style experience with added AI-driven features.",
      tags: ["In Progress", "AI"],
      category: "Web Application, Mobile Application",
      link: "https://github.com/itisFAHIM/RickShare-Main",
      image: "images/Rickshare.png"
    }
  ],
  lens: [
    { image: "assets/Main page image/1 (109).jpg", label: "Street Life / 2024" },
    { image: "assets/Main page image/1 (17).jpg", label: "Nature Escapes" },
    { image: "assets/Main page image/1 (174).jpg", label: "Creative Portraits" },
    { image: "assets/Main page image/1 (175).jpg", label: "Fast Paced Action" },
    { image: "assets/Main page image/1 (184).jpg", label: "Urban Stories" },
    { image: "assets/Main page image/1 (20).jpg", label: "Scenic Views" },
    { image: "assets/Main page image/1 (22).jpg", label: "Studio Work" },
    { image: "assets/Main page image/1 (23).jpg", label: "Dynamic Motion" },
    { image: "assets/Main page image/1 (50).jpg", label: "Visual Arts" },
    { image: "assets/Main page image/1 (68).jpg", label: "City Vibes" },
    { image: "assets/Main page image/1 (84).jpg", label: "Captured Moments" },
    { image: "assets/Main page image/1 (86).jpg", label: "Raw Perspective" }
  ],
  awards: [
    { name: "Runner-Up — ICCIT 2023 Student Activity Video Contest", year: "2023" },
    { name: "Xiaomi Global Photography Contest — Regional Top 50 / Bangladesh Top 10", year: "2024" },
    { name: "Nikon Film & Photo Contest — Regional Top 100 / Bangladesh 3rd", year: "2022–23" },
    { name: "IEEE DAY 2025 Ambassador Region 10 — North South University", year: "2025" }
  ],
  education: [
    {
      date: "2021 — Present",
      school: "North South University, Dhaka",
      degree: "B.Sc. in Computer Science & Engineering"
    },
    {
      date: "2018 — 2020",
      school: "Ideal College, Dhanmondi, Dhaka",
      degree: "Higher Secondary School Certificate"
    },
    {
      date: "2016 — 2018",
      school: "Nabakumar Institution & Dr. Shahidullah College, Dhaka",
      degree: "Secondary School Certificate"
    },
    {
      date: "2013 — 2015",
      school: "Govt. Technical High School, Noakhali",
      degree: "Junior School Certificate"
    }
  ],
  photography: [
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (1).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (102).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (106).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (11).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (11).png' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (119).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (12).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (121).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (123).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (124).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (125).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (13).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (13).png' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (133).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (141).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (145).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (15).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (157).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (16).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (161).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (164).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (165).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (168).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (169).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (17).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (170).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (172).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (173).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (18).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (184).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (186).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (187).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (188).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (190).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (193).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (194).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (196).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (197).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (198).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (199).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (20).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (200).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (201).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (208).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (209).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (21).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (210).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (211).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (22).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (23).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (27).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (29).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (30).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (31).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (32).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (34).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (35).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (36).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (38).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (40).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (41).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (42).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (43).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (44).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (46).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (47).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (48).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (49).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (5).png' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (50).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (52).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (53).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (54).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (55).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (56).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (57).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (6).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (6).png' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (62).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (64).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (65).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (66).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (67).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (68).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (70).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (71).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (73).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (75).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (76).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (8).png' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (80).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (82).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (85).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (86).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (87).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (9).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (9).png' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (91).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/1 (94).jpg' },
    { category: 'landscape', title: 'Captured Moment', image: 'assets/Landscape/DSC04798.JPG' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (103).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (112).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (114).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (115).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (12).png' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (122).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (123).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (127).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (128).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (129).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (130).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (132).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (135).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (136).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (137).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (14).png' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (140).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (144).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (148).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (15).png' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (150).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (154).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (159).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (161).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (166).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (174).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (177).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (178).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (179).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (180).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (184).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (19).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (190).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (191).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (192).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (2).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (201).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (207).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (23).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (24).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (25).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (3).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (33).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (35).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (37).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (39).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (4).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (4).png' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (57).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (59).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (60).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (61).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (69).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (72).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (79).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (84).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (86).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (89).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (9).png' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (90).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (93).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (95).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (96).jpg' },
    { category: 'street', title: 'Captured Moment', image: 'assets/Street/1 (98).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (109).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (117).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (131).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (147).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (166).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (177).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (2).jpeg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (2).png' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (68).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (89).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (92).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/1 (95).jpg' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/DSC04788.JPG' },
    { category: 'portrait', title: 'Captured Moment', image: 'assets/Potrait/DSC04795.JPG' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (10).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (117).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (121).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (126).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (127).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (130).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (132).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (139).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (153).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (160).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (162).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (163).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (175).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (2).jpeg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (28).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (45).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (49).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (55).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (59).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (60).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (68).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (71).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (72).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (74).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (77).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (80).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (88).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (89).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (90).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/1 (98).jpg' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/DSC04788.JPG' },
    { category: 'action', title: 'Captured Moment', image: 'assets/Action/DSC04795.JPG' }
  ],
  videography: [
    { title: 'Hackathon', image: 'assets/Videos/Hackathon.png', link: 'https://www.facebook.com/reel/1191278535784709' },
    { title: 'Logo Reveal', image: 'assets/Videos/Logo Reveal.png', link: 'https://www.facebook.com/reel/2818147411721211' },
    { title: 'Event Promo', image: 'assets/Videos/Event promo.png', link: 'https://www.facebook.com/reel/1502636490371917' },
    { title: 'Coming Soon Suspense', image: 'assets/Videos/Coming Soon Suspense.png', link: 'https://www.facebook.com/reel/3847607838894210' },
    { title: 'Website Promo', image: 'assets/Videos/Website Promo.png', link: 'https://www.facebook.com/reel/782495030466281' },
    { title: 'Memories', image: 'assets/Videos/Memories.png', link: 'https://www.facebook.com/reel/704582078229009' },
    { title: 'Teaser', image: 'assets/Videos/Teaser.png', link: 'https://www.facebook.com/reel/871892824571719' },
    { title: 'INSB Recruitment', image: 'assets/Videos/Short Film/INSB recruitment .png', link: 'https://www.facebook.com/reel/925162386323487' },
    { title: 'Kache Ashar Golpo Page', image: 'assets/Videos/Short Film/Kache Ashar Golpo  Page.jpg', link: 'https://youtu.be/52U48xsfGHw?si=NErw65JPnWaVjPem' },

    { title: 'Kache Ashar Golpo Kodom', image: 'assets/Videos/Short Film/Kache Ashar Golpo Kodom.jpg', link: 'https://youtu.be/sl1DxUs-OfM?si=uO74vabMwF8YQrmO' },
    { title: 'Kache Ashar Golpo Metro', image: 'assets/Videos/Short Film/Kache Ashar Golpo Metro.jpg', link: 'https://youtu.be/FJ9ikW_hdAM?si=HoQLMm7dgqFZy2hq' },
    { title: 'Kache Ashar Golpo Ojana', image: 'assets/Videos/Short Film/Kache Ashar Golpo Ojana.jpg', link: 'https://youtu.be/WGnCS32iriU?si=SozIrZ19IDo80ufC' },
    { title: 'Organization Promo', image: 'assets/Videos/Organization Promo .png', link: 'https://www.facebook.com/reel/1173887430234383' },
    { title: 'Ticking', image: 'assets/Videos/Ticking.png', link: 'https://www.facebook.com/reel/591535386701843' },
    { title: 'Spac 24', image: 'assets/Videos/Spac 24.png', link: 'https://www.facebook.com/reel/937306991596331' },
    { title: 'Kache Ashar Golpo Jodi Abar', image: 'assets/Videos/Short Film/Kache Ashar Golpo Jodi Abar.jpg', link: 'https://youtu.be/-43B5SPHNHw?si=zVB27_zOnP0iTY1F' },
    { title: 'Sponsor', image: 'assets/Videos/Sponsor.png', link: 'https://drive.google.com/file/d/1tYcJOQOA7ZPQ4p7dIfF06cLFn_-XOpL-/view?usp=sharing' },
    { title: 'Load', image: 'assets/Videos/Short Film/Load.jpg', link: 'https://www.youtube.com/watch?v=ixd654b4MDo' }
  ]
};
